# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/ntu/xsub/val_data_joint.npy
  label_path: ./data/ntu/xsub/val_label.pkl
  debug: False

# model
model: model.lgcn.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

# test
phase: test
device: [0, 1, 2, 3]
test_batch_size: 16
weights: ./runs/ntu_cs_lgcn_joint/ntu_cs_lgcn_joint-41-26292.pt

work_dir: ./work_dir/ntu/xsub/lgcn_test_joint
model_saved_name: ./runs/ntu_cs_lgcn_test_joint
save_score: True
